/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author dell
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addstudentBtn1 = new javax.swing.JButton();
        addstudentBtn2 = new javax.swing.JButton();
        addstudentBtn3 = new javax.swing.JButton();
        addstudentBtn4 = new javax.swing.JButton();
        addstudentBtn5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("WELCOME TO,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 80));

        jLabel3.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel3.setText(" interactive activities, workshops, and discussions.\"");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 390, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel4.setText("MASTER MINDS ENGLISH CLUB");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 80));

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel5.setText("\"Master Minds English Club offers a dynamic and engaging environment for language learners of all levels.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 810, 20));

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 18)); // NOI18N
        jLabel6.setText("We provide a platform for members to improve their speaking, writing, reading, and listening skills through ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 810, 20));

        addstudentBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addstudentBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/add-user_1250346.png"))); // NOI18N
        addstudentBtn1.setBorder(null);
        addstudentBtn1.setBorderPainted(false);
        addstudentBtn1.setContentAreaFilled(false);
        addstudentBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 240, 190));

        addstudentBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/logout.png"))); // NOI18N
        addstudentBtn2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addstudentBtn2.setBorderPainted(false);
        addstudentBtn2.setContentAreaFilled(false);
        addstudentBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 290, 240, 190));

        addstudentBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/friendlist_6866291.png"))); // NOI18N
        addstudentBtn3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addstudentBtn3.setBorderPainted(false);
        addstudentBtn3.setContentAreaFilled(false);
        addstudentBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 240, 190));

        addstudentBtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/payment.png"))); // NOI18N
        addstudentBtn4.setBorder(null);
        addstudentBtn4.setBorderPainted(false);
        addstudentBtn4.setContentAreaFilled(false);
        addstudentBtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 290, 240, 190));

        addstudentBtn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/writing_1251587.png"))); // NOI18N
        addstudentBtn5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        addstudentBtn5.setBorderPainted(false);
        addstudentBtn5.setContentAreaFilled(false);
        addstudentBtn5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addstudentBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentBtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(addstudentBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 240, 190));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel2.setText("Logout");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel7.setText("Add Student");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel8.setText("Update & Delete ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel9.setText("Student List");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 16)); // NOI18N
        jLabel10.setText("Payments");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 460, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Homepage images/close.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1470, 770));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 830));

        setSize(new java.awt.Dimension(1528, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addstudentBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_addstudentBtn1ActionPerformed

    private void addstudentBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn2ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_addstudentBtn2ActionPerformed

    private void addstudentBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn3ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new ListofStudents().setVisible(true);
    }//GEN-LAST:event_addstudentBtn3ActionPerformed

    private void addstudentBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn4ActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        new Payment().setVisible(true);
    }//GEN-LAST:event_addstudentBtn4ActionPerformed

    private void addstudentBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentBtn5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateDelete().setVisible(true);
    }//GEN-LAST:event_addstudentBtn5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addstudentBtn1;
    private javax.swing.JButton addstudentBtn2;
    private javax.swing.JButton addstudentBtn3;
    private javax.swing.JButton addstudentBtn4;
    private javax.swing.JButton addstudentBtn5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
